export type HousekeepingRecord = {
  id: string;
  roomName: string;
  resortName: string;
  tenantName: string;
  roomCategory: "Villa" | "Suite" | "Casita" | "Family Room" | "Deluxe Room";
  serviceType: "Checkout Turnover" | "Stayover Refresh" | "Deep Clean" | "Inspection";
  housekeepingStatus: "Queued" | "Cleaning" | "Inspection" | "Completed" | "Blocked";
  readinessStatus: "Ready" | "Not Ready" | "Awaiting Inspection";
  occupancyContext: "Arrival Today" | "In House" | "Checkout Due" | "Vacant";
  assignedTo: string;
  dueWindow: string;
  lastUpdated: string;
  blocker: string;
  priority: boolean;
};

export const housekeepingRecords: HousekeepingRecord[] = [
  {
    id: "HK-5201",
    roomName: "Family Villa 2",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    roomCategory: "Villa",
    serviceType: "Checkout Turnover",
    housekeepingStatus: "Cleaning",
    readinessStatus: "Not Ready",
    occupancyContext: "Arrival Today",
    assignedTo: "Rhea Tolentino",
    dueWindow: "Before 2:00 PM",
    lastUpdated: "5 mins ago",
    blocker: "Linen replacement in progress",
    priority: true,
  },
  {
    id: "HK-5202",
    roomName: "Pool Villa 1",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    roomCategory: "Villa",
    serviceType: "Inspection",
    housekeepingStatus: "Inspection",
    readinessStatus: "Awaiting Inspection",
    occupancyContext: "Arrival Today",
    assignedTo: "Maya Dizon",
    dueWindow: "Before 1:30 PM",
    lastUpdated: "12 mins ago",
    blocker: "Supervisor clearance pending",
    priority: true,
  },
  {
    id: "HK-5203",
    roomName: "Garden Suite 4",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    roomCategory: "Suite",
    serviceType: "Stayover Refresh",
    housekeepingStatus: "Queued",
    readinessStatus: "Not Ready",
    occupancyContext: "In House",
    assignedTo: "Liza Mercado",
    dueWindow: "Before 3:00 PM",
    lastUpdated: "18 mins ago",
    blocker: "Guest requested late service",
    priority: false,
  },
  {
    id: "HK-5204",
    roomName: "Casita 8",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    roomCategory: "Casita",
    serviceType: "Deep Clean",
    housekeepingStatus: "Blocked",
    readinessStatus: "Not Ready",
    occupancyContext: "Vacant",
    assignedTo: "Jules Navarro",
    dueWindow: "Before 5:00 PM",
    lastUpdated: "24 mins ago",
    blocker: "Maintenance hold on bathroom fixture",
    priority: true,
  },
  {
    id: "HK-5205",
    roomName: "Verde Villa 3",
    resortName: "Casa Verde Private Villas",
    tenantName: "Casa Verde Leisure",
    roomCategory: "Villa",
    serviceType: "Checkout Turnover",
    housekeepingStatus: "Completed",
    readinessStatus: "Ready",
    occupancyContext: "Arrival Today",
    assignedTo: "Irene Valdez",
    dueWindow: "Closed at 11:40 AM",
    lastUpdated: "9 mins ago",
    blocker: "No active blocker",
    priority: false,
  },
  {
    id: "HK-5206",
    roomName: "Isla Deluxe 2",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    roomCategory: "Deluxe Room",
    serviceType: "Checkout Turnover",
    housekeepingStatus: "Cleaning",
    readinessStatus: "Not Ready",
    occupancyContext: "Checkout Due",
    assignedTo: "Anne Bautista",
    dueWindow: "Before 12:30 PM",
    lastUpdated: "14 mins ago",
    blocker: "Mini bar count not finished",
    priority: false,
  },
  {
    id: "HK-5207",
    roomName: "Reef Suite 6",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    roomCategory: "Suite",
    serviceType: "Stayover Refresh",
    housekeepingStatus: "Completed",
    readinessStatus: "Ready",
    occupancyContext: "In House",
    assignedTo: "Grace Fernandez",
    dueWindow: "Closed at 10:55 AM",
    lastUpdated: "8 mins ago",
    blocker: "No active blocker",
    priority: false,
  },
  {
    id: "HK-5208",
    roomName: "Coral Family 1",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    roomCategory: "Family Room",
    serviceType: "Checkout Turnover",
    housekeepingStatus: "Inspection",
    readinessStatus: "Awaiting Inspection",
    occupancyContext: "Arrival Today",
    assignedTo: "Grace Fernandez",
    dueWindow: "Before 1:00 PM",
    lastUpdated: "17 mins ago",
    blocker: "Final amenity check pending",
    priority: true,
  },
  {
    id: "HK-5209",
    roomName: "Bayfront Suite 5",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    roomCategory: "Suite",
    serviceType: "Checkout Turnover",
    housekeepingStatus: "Queued",
    readinessStatus: "Not Ready",
    occupancyContext: "Checkout Due",
    assignedTo: "Mark Sison",
    dueWindow: "Before 2:30 PM",
    lastUpdated: "26 mins ago",
    blocker: "Waiting for checkout release",
    priority: false,
  },
  {
    id: "HK-5210",
    roomName: "Peak Villa 2",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    roomCategory: "Villa",
    serviceType: "Deep Clean",
    housekeepingStatus: "Blocked",
    readinessStatus: "Not Ready",
    occupancyContext: "Vacant",
    assignedTo: "Ela Gomez",
    dueWindow: "Before 4:00 PM",
    lastUpdated: "31 mins ago",
    blocker: "Odor treatment still scheduled",
    priority: true,
  },
];
