export type HrRecord = {
  id: string;
  employeeName: string;
  resortName: string;
  tenantName: string;
  department:
    | "Front Desk"
    | "Housekeeping"
    | "Maintenance"
    | "Food Service"
    | "Guest Experience"
    | "Security";
  roleTitle: string;
  workforceStatus: "On Shift" | "Late" | "Off Duty" | "Leave" | "Open Role";
  staffingRisk: "Stable" | "Watch" | "Critical";
  attendanceStatus: "Present" | "Late" | "Leave" | "Vacant";
  shiftWindow: string;
  assignedManager: string;
  hrNote: string;
  lastUpdated: string;
  priority: boolean;
};

export const hrRecords: HrRecord[] = [
  {
    id: "HR-8101",
    employeeName: "Mika Dela Cruz",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    department: "Front Desk",
    roleTitle: "Senior Front Desk Agent",
    workforceStatus: "On Shift",
    staffingRisk: "Stable",
    attendanceStatus: "Present",
    shiftWindow: "6:00 AM - 2:00 PM",
    assignedManager: "Celina Torres",
    hrNote: "Leading early-arrival queue coverage today",
    lastUpdated: "5 mins ago",
    priority: false,
  },
  {
    id: "HR-8102",
    employeeName: "Kurt Mendoza",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    department: "Housekeeping",
    roleTitle: "Housekeeping Supervisor",
    workforceStatus: "Late",
    staffingRisk: "Watch",
    attendanceStatus: "Late",
    shiftWindow: "7:00 AM - 3:00 PM",
    assignedManager: "Lorna Aguilar",
    hrNote: "Team briefing delayed by transport issue",
    lastUpdated: "11 mins ago",
    priority: true,
  },
  {
    id: "HR-8103",
    employeeName: "Joel Ramirez",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    department: "Maintenance",
    roleTitle: "Engineering Technician",
    workforceStatus: "On Shift",
    staffingRisk: "Stable",
    attendanceStatus: "Present",
    shiftWindow: "8:00 AM - 5:00 PM",
    assignedManager: "Victor Sison",
    hrNote: "Assigned to high-priority HVAC calls",
    lastUpdated: "7 mins ago",
    priority: false,
  },
  {
    id: "HR-8104",
    employeeName: "Open Position",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    department: "Guest Experience",
    roleTitle: "Activities Coordinator",
    workforceStatus: "Open Role",
    staffingRisk: "Critical",
    attendanceStatus: "Vacant",
    shiftWindow: "Peak weekends",
    assignedManager: "Jules Serrano",
    hrNote: "Open requisition is affecting diving activity coverage",
    lastUpdated: "19 mins ago",
    priority: true,
  },
  {
    id: "HR-8105",
    employeeName: "Dana Reyes",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    department: "Front Desk",
    roleTitle: "Guest Services Agent",
    workforceStatus: "On Shift",
    staffingRisk: "Watch",
    attendanceStatus: "Present",
    shiftWindow: "2:00 PM - 10:00 PM",
    assignedManager: "Paula Ramos",
    hrNote: "Requested same-day schedule adjustment",
    lastUpdated: "14 mins ago",
    priority: false,
  },
  {
    id: "HR-8106",
    employeeName: "Grace Fernandez",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    department: "Housekeeping",
    roleTitle: "Room Attendant Lead",
    workforceStatus: "On Shift",
    staffingRisk: "Stable",
    attendanceStatus: "Present",
    shiftWindow: "7:00 AM - 4:00 PM",
    assignedManager: "Lina Bautista",
    hrNote: "Supporting inspection-heavy turnover board",
    lastUpdated: "8 mins ago",
    priority: false,
  },
  {
    id: "HR-8107",
    employeeName: "Open Position",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    department: "Food Service",
    roleTitle: "Restaurant Supervisor",
    workforceStatus: "Open Role",
    staffingRisk: "Critical",
    attendanceStatus: "Vacant",
    shiftWindow: "Lunch and dinner peak",
    assignedManager: "Mina Torres",
    hrNote: "Interim lead is covering two meal periods",
    lastUpdated: "23 mins ago",
    priority: true,
  },
  {
    id: "HR-8108",
    employeeName: "Noel Castro",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    department: "Security",
    roleTitle: "Security Supervisor",
    workforceStatus: "Leave",
    staffingRisk: "Watch",
    attendanceStatus: "Leave",
    shiftWindow: "Night shift recovery",
    assignedManager: "Bernard Cruz",
    hrNote: "Medical leave filed and approved for 2 days",
    lastUpdated: "17 mins ago",
    priority: false,
  },
  {
    id: "HR-8109",
    employeeName: "Anne Bautista",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    department: "Housekeeping",
    roleTitle: "Room Attendant",
    workforceStatus: "On Shift",
    staffingRisk: "Stable",
    attendanceStatus: "Present",
    shiftWindow: "7:00 AM - 3:00 PM",
    assignedManager: "Lorna Flores",
    hrNote: "Cross-assigned to support shuttle-side villas",
    lastUpdated: "9 mins ago",
    priority: false,
  },
  {
    id: "HR-8110",
    employeeName: "Rico Santos",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    department: "Guest Experience",
    roleTitle: "Concierge Associate",
    workforceStatus: "Late",
    staffingRisk: "Watch",
    attendanceStatus: "Late",
    shiftWindow: "9:00 AM - 6:00 PM",
    assignedManager: "Aris Flores",
    hrNote: "Needs attendance note before payroll cutoff",
    lastUpdated: "13 mins ago",
    priority: true,
  },
];
