export type FrontdeskRecord = {
  id: string;
  guestName: string;
  reservationCode: string;
  resortName: string;
  tenantName: string;
  roomName: string;
  arrivalDate: string;
  departureDate: string;
  queueStage: "Arrival Today" | "Check-In Pending" | "In House" | "Checkout Due";
  frontdeskStatus: "Ready" | "Waiting Payment" | "Room Not Ready" | "Needs ID Review";
  paymentStatus: "Settled" | "Partial" | "Outstanding";
  roomReadiness: "Ready" | "Cleaning" | "Inspection";
  conciergeFlag: "Standard" | "VIP" | "Group";
  assignee: string;
  lastUpdated: string;
  priority: boolean;
};

export const frontdeskRecords: FrontdeskRecord[] = [
  {
    id: "FD-4101",
    guestName: "Andrea Santos",
    reservationCode: "ALR-2041",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    roomName: "Family Villa 2",
    arrivalDate: "Apr 25, 2026",
    departureDate: "Apr 27, 2026",
    queueStage: "Check-In Pending",
    frontdeskStatus: "Waiting Payment",
    paymentStatus: "Partial",
    roomReadiness: "Ready",
    conciergeFlag: "VIP",
    assignee: "Mika Dela Cruz",
    lastUpdated: "4 mins ago",
    priority: true,
  },
  {
    id: "FD-4102",
    guestName: "Claire Dizon",
    reservationCode: "AZP-1829",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    roomName: "Garden Suite 4",
    arrivalDate: "Apr 25, 2026",
    departureDate: "Apr 28, 2026",
    queueStage: "Arrival Today",
    frontdeskStatus: "Room Not Ready",
    paymentStatus: "Settled",
    roomReadiness: "Cleaning",
    conciergeFlag: "Standard",
    assignee: "Kurt Mendoza",
    lastUpdated: "11 mins ago",
    priority: true,
  },
  {
    id: "FD-4103",
    guestName: "Paolo Navarro",
    reservationCode: "BRE-1172",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    roomName: "Coral Family 1",
    arrivalDate: "Apr 25, 2026",
    departureDate: "Apr 29, 2026",
    queueStage: "Check-In Pending",
    frontdeskStatus: "Ready",
    paymentStatus: "Settled",
    roomReadiness: "Ready",
    conciergeFlag: "Group",
    assignee: "Jessa Cruz",
    lastUpdated: "7 mins ago",
    priority: false,
  },
  {
    id: "FD-4104",
    guestName: "Michael Lim",
    reservationCode: "AZC-0883",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    roomName: "Casita 8",
    arrivalDate: "Apr 24, 2026",
    departureDate: "Apr 26, 2026",
    queueStage: "In House",
    frontdeskStatus: "Needs ID Review",
    paymentStatus: "Outstanding",
    roomReadiness: "Ready",
    conciergeFlag: "Standard",
    assignee: "Dana Reyes",
    lastUpdated: "18 mins ago",
    priority: true,
  },
  {
    id: "FD-4105",
    guestName: "Nica Gomez",
    reservationCode: "CPR-0941",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    roomName: "Peak Villa 2",
    arrivalDate: "Apr 25, 2026",
    departureDate: "Apr 27, 2026",
    queueStage: "Arrival Today",
    frontdeskStatus: "Room Not Ready",
    paymentStatus: "Settled",
    roomReadiness: "Inspection",
    conciergeFlag: "VIP",
    assignee: "Lourdes Tan",
    lastUpdated: "22 mins ago",
    priority: true,
  },
  {
    id: "FD-4106",
    guestName: "Jonas Velasco",
    reservationCode: "CVL-1307",
    resortName: "Casa Verde Private Villas",
    tenantName: "Casa Verde Leisure",
    roomName: "Verde Villa 3",
    arrivalDate: "Apr 25, 2026",
    departureDate: "Apr 30, 2026",
    queueStage: "Check-In Pending",
    frontdeskStatus: "Ready",
    paymentStatus: "Settled",
    roomReadiness: "Ready",
    conciergeFlag: "Standard",
    assignee: "Ana Garcia",
    lastUpdated: "9 mins ago",
    priority: false,
  },
  {
    id: "FD-4107",
    guestName: "Rina Bautista",
    reservationCode: "IJR-2104",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    roomName: "Isla Deluxe 2",
    arrivalDate: "Apr 25, 2026",
    departureDate: "Apr 26, 2026",
    queueStage: "Arrival Today",
    frontdeskStatus: "Waiting Payment",
    paymentStatus: "Outstanding",
    roomReadiness: "Ready",
    conciergeFlag: "Standard",
    assignee: "Rico Santos",
    lastUpdated: "13 mins ago",
    priority: true,
  },
  {
    id: "FD-4108",
    guestName: "Mara Ong",
    reservationCode: "BFH-1098",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    roomName: "Bayfront Suite 5",
    arrivalDate: "Apr 23, 2026",
    departureDate: "Apr 25, 2026",
    queueStage: "Checkout Due",
    frontdeskStatus: "Ready",
    paymentStatus: "Partial",
    roomReadiness: "Ready",
    conciergeFlag: "Standard",
    assignee: "Neil Flores",
    lastUpdated: "15 mins ago",
    priority: false,
  },
  {
    id: "FD-4109",
    guestName: "The Ramos Family",
    reservationCode: "ALR-2054",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    roomName: "Pool Villa 1",
    arrivalDate: "Apr 25, 2026",
    departureDate: "Apr 27, 2026",
    queueStage: "Arrival Today",
    frontdeskStatus: "Needs ID Review",
    paymentStatus: "Settled",
    roomReadiness: "Inspection",
    conciergeFlag: "Group",
    assignee: "Mika Dela Cruz",
    lastUpdated: "29 mins ago",
    priority: true,
  },
  {
    id: "FD-4110",
    guestName: "Leo Gutierrez",
    reservationCode: "BRE-1181",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    roomName: "Reef Suite 6",
    arrivalDate: "Apr 24, 2026",
    departureDate: "Apr 26, 2026",
    queueStage: "In House",
    frontdeskStatus: "Ready",
    paymentStatus: "Settled",
    roomReadiness: "Ready",
    conciergeFlag: "VIP",
    assignee: "Jessa Cruz",
    lastUpdated: "6 mins ago",
    priority: false,
  },
];
