export type RateRecord = {
  id: string;
  roomName: string;
  resortName: string;
  tenantName: string;
  category: "Villa" | "Suite" | "Casita" | "Family Room" | "Deluxe Room";
  baseRate: number;
  weekendRate: number;
  promoRate: number;
  channelRate: number;
  pricingStatus: "Optimized" | "Needs Review" | "Promo Live";
  demandSignal: "High" | "Medium" | "Low";
  lastRateUpdate: string;
  activePromo: string;
  priority: boolean;
};

export const rateRecords: RateRecord[] = [
  {
    id: "RT-4001",
    roomName: "Family Villa 2",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    category: "Villa",
    baseRate: 12800,
    weekendRate: 14400,
    promoRate: 11900,
    channelRate: 13600,
    pricingStatus: "Promo Live",
    demandSignal: "High",
    lastRateUpdate: "18 mins ago",
    activePromo: "Midweek Family Offer",
    priority: true,
  },
  {
    id: "RT-4002",
    roomName: "Pool Villa 1",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    category: "Villa",
    baseRate: 16200,
    weekendRate: 17900,
    promoRate: 0,
    channelRate: 17100,
    pricingStatus: "Optimized",
    demandSignal: "High",
    lastRateUpdate: "42 mins ago",
    activePromo: "None",
    priority: true,
  },
  {
    id: "RT-4003",
    roomName: "Garden Suite 4",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    category: "Suite",
    baseRate: 8950,
    weekendRate: 9800,
    promoRate: 8200,
    channelRate: 9350,
    pricingStatus: "Promo Live",
    demandSignal: "Medium",
    lastRateUpdate: "1 hr ago",
    activePromo: "Advance Booking Deal",
    priority: false,
  },
  {
    id: "RT-4004",
    roomName: "Casita 8",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    category: "Casita",
    baseRate: 5800,
    weekendRate: 6400,
    promoRate: 0,
    channelRate: 6200,
    pricingStatus: "Needs Review",
    demandSignal: "Low",
    lastRateUpdate: "3 hrs ago",
    activePromo: "None",
    priority: true,
  },
  {
    id: "RT-4005",
    roomName: "Verde Villa 3",
    resortName: "Casa Verde Private Villas",
    tenantName: "Casa Verde Leisure",
    category: "Villa",
    baseRate: 11600,
    weekendRate: 12900,
    promoRate: 10800,
    channelRate: 12100,
    pricingStatus: "Optimized",
    demandSignal: "Medium",
    lastRateUpdate: "2 hrs ago",
    activePromo: "Direct Booking Saver",
    priority: false,
  },
  {
    id: "RT-4006",
    roomName: "Isla Deluxe 2",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    category: "Deluxe Room",
    baseRate: 6400,
    weekendRate: 7100,
    promoRate: 5900,
    channelRate: 6700,
    pricingStatus: "Promo Live",
    demandSignal: "Low",
    lastRateUpdate: "56 mins ago",
    activePromo: "Island Escape Offer",
    priority: false,
  },
  {
    id: "RT-4007",
    roomName: "Reef Suite 6",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    category: "Suite",
    baseRate: 9800,
    weekendRate: 10800,
    promoRate: 0,
    channelRate: 10200,
    pricingStatus: "Optimized",
    demandSignal: "High",
    lastRateUpdate: "26 mins ago",
    activePromo: "None",
    priority: false,
  },
  {
    id: "RT-4008",
    roomName: "Coral Family 1",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    category: "Family Room",
    baseRate: 11200,
    weekendRate: 12400,
    promoRate: 10300,
    channelRate: 11700,
    pricingStatus: "Promo Live",
    demandSignal: "High",
    lastRateUpdate: "35 mins ago",
    activePromo: "Weekend Family Bundle",
    priority: true,
  },
  {
    id: "RT-4009",
    roomName: "Bayfront Suite 5",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    category: "Suite",
    baseRate: 7600,
    weekendRate: 8350,
    promoRate: 0,
    channelRate: 7950,
    pricingStatus: "Optimized",
    demandSignal: "Medium",
    lastRateUpdate: "1 hr ago",
    activePromo: "None",
    priority: false,
  },
  {
    id: "RT-4010",
    roomName: "Peak Villa 2",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    category: "Villa",
    baseRate: 13400,
    weekendRate: 14900,
    promoRate: 0,
    channelRate: 14100,
    pricingStatus: "Needs Review",
    demandSignal: "Low",
    lastRateUpdate: "4 hrs ago",
    activePromo: "None",
    priority: true,
  },
];
