export type InvoiceRecord = {
  id: string;
  tenantName: string;
  resortName: string;
  invoiceTitle: string;
  invoiceSource: "Automatic" | "Manual";
  invoiceCategory:
    | "Plan Subscription"
    | "Add-on Charge"
    | "SMS Overage"
    | "Setup Fee"
    | "Support Upgrade";
  invoiceStatus: "Draft" | "Issued" | "Due Soon" | "Overdue" | "Paid";
  amount: number;
  dueDate: string;
  billingPeriod: string;
  paymentStatus: "Clear" | "Watch" | "At Risk";
  assignedTo: string;
  note: string;
  priority: boolean;
};

export const invoiceRecords: InvoiceRecord[] = [
  {
    id: "INV-3101",
    tenantName: "Alrio Hospitality Group",
    resortName: "Alrio Resort Batangas",
    invoiceTitle: "Enterprise plan renewal",
    invoiceSource: "Automatic",
    invoiceCategory: "Plan Subscription",
    invoiceStatus: "Due Soon",
    amount: 95880,
    dueDate: "Apr 30, 2026",
    billingPeriod: "Apr 2026 - Apr 2027",
    paymentStatus: "Watch",
    assignedTo: "Kara Mendoza",
    note: "Auto-generated annual renewal invoice pending tenant PO confirmation.",
    priority: true,
  },
  {
    id: "INV-3102",
    tenantName: "Azure Palms Hospitality",
    resortName: "Azure Palms Resort",
    invoiceTitle: "Growth monthly subscription",
    invoiceSource: "Automatic",
    invoiceCategory: "Plan Subscription",
    invoiceStatus: "Overdue",
    amount: 5999,
    dueDate: "Apr 22, 2026",
    billingPeriod: "Apr 2026",
    paymentStatus: "At Risk",
    assignedTo: "Liza Ong",
    note: "Recurring plan invoice remains unpaid after two retry attempts.",
    priority: true,
  },
  {
    id: "INV-3103",
    tenantName: "Casa Verde Leisure",
    resortName: "Casa Verde Private Villas",
    invoiceTitle: "Onboarding setup fee",
    invoiceSource: "Manual",
    invoiceCategory: "Setup Fee",
    invoiceStatus: "Issued",
    amount: 12000,
    dueDate: "May 05, 2026",
    billingPeriod: "One-time",
    paymentStatus: "Clear",
    assignedTo: "Mira Valdez",
    note: "Manual invoice created for implementation and migration support.",
    priority: false,
  },
  {
    id: "INV-3104",
    tenantName: "Blue Reef Escapes",
    resortName: "Blue Reef Escapes",
    invoiceTitle: "Starter monthly subscription",
    invoiceSource: "Automatic",
    invoiceCategory: "Plan Subscription",
    invoiceStatus: "Paid",
    amount: 2499,
    dueDate: "May 05, 2026",
    billingPeriod: "Apr 2026",
    paymentStatus: "Clear",
    assignedTo: "Janine Castro",
    note: "Subscription invoice settled successfully through stored card billing.",
    priority: false,
  },
  {
    id: "INV-3105",
    tenantName: "Coral Peak Resorts",
    resortName: "Coral Peak Resorts",
    invoiceTitle: "SMS usage overage",
    invoiceSource: "Manual",
    invoiceCategory: "SMS Overage",
    invoiceStatus: "Draft",
    amount: 3500,
    dueDate: "May 08, 2026",
    billingPeriod: "Apr 2026",
    paymentStatus: "Watch",
    assignedTo: "Mina Torres",
    note: "Pending review before releasing extra SMS volume charges.",
    priority: true,
  },
  {
    id: "INV-3106",
    tenantName: "Bayfront Hideaway",
    resortName: "Bayfront Hideaway",
    invoiceTitle: "Starter monthly subscription",
    invoiceSource: "Automatic",
    invoiceCategory: "Plan Subscription",
    invoiceStatus: "Overdue",
    amount: 2499,
    dueDate: "Apr 18, 2026",
    billingPeriod: "Apr 2026",
    paymentStatus: "At Risk",
    assignedTo: "Noel Ramos",
    note: "Automatic invoice is overdue while billing method update is still pending.",
    priority: true,
  },
  {
    id: "INV-3107",
    tenantName: "Isla Jardin Retreats",
    resortName: "Isla Jardin Suites",
    invoiceTitle: "Growth annual subscription",
    invoiceSource: "Automatic",
    invoiceCategory: "Plan Subscription",
    invoiceStatus: "Paid",
    amount: 71988,
    dueDate: "Jan 14, 2026",
    billingPeriod: "Jan 2026 - Jan 2027",
    paymentStatus: "Clear",
    assignedTo: "Rica Flores",
    note: "Annual subscription invoice settled and archived for current term.",
    priority: false,
  },
  {
    id: "INV-3108",
    tenantName: "Peak Wellness Collection",
    resortName: "Peak Wellness Suites",
    invoiceTitle: "Premium support upgrade",
    invoiceSource: "Manual",
    invoiceCategory: "Support Upgrade",
    invoiceStatus: "Issued",
    amount: 8900,
    dueDate: "May 03, 2026",
    billingPeriod: "Q2 2026",
    paymentStatus: "Watch",
    assignedTo: "Mina Torres",
    note: "Manual charge for quarterly support uplift and advisory coverage.",
    priority: false,
  },
  {
    id: "INV-3109",
    tenantName: "Suncrest Cove Hospitality",
    resortName: "Suncrest Cove Villas",
    invoiceTitle: "Starter monthly subscription",
    invoiceSource: "Automatic",
    invoiceCategory: "Plan Subscription",
    invoiceStatus: "Draft",
    amount: 2499,
    dueDate: "May 03, 2026",
    billingPeriod: "May 2026",
    paymentStatus: "Clear",
    assignedTo: "Aira Santos",
    note: "Next recurring invoice is generated and waiting final usage adjustments.",
    priority: false,
  },
  {
    id: "INV-3110",
    tenantName: "Verde Haven Resorts",
    resortName: "Verde Haven Residences",
    invoiceTitle: "Channel manager add-on",
    invoiceSource: "Manual",
    invoiceCategory: "Add-on Charge",
    invoiceStatus: "Due Soon",
    amount: 14500,
    dueDate: "May 15, 2026",
    billingPeriod: "Apr 2026",
    paymentStatus: "Watch",
    assignedTo: "Cleo Rivera",
    note: "Manual add-on invoice for premium distribution and channel sync access.",
    priority: true,
  },
];
