export type MaintenanceRecord = {
  id: string;
  roomName: string;
  resortName: string;
  tenantName: string;
  issueCategory: "Electrical" | "Plumbing" | "HVAC" | "Furniture" | "General Repair";
  workOrderType: "Guest Reported" | "Preventive" | "Turnover Repair" | "Facility Check";
  maintenanceStatus: "Open" | "In Progress" | "Awaiting Parts" | "For Verification" | "Resolved";
  severity: "Low" | "Medium" | "High" | "Critical";
  roomImpact: "Sellable" | "Limited" | "Out of Order";
  assignedTo: string;
  dueWindow: string;
  blocker: string;
  reportedBy: string;
  lastUpdated: string;
  priority: boolean;
};

export const maintenanceRecords: MaintenanceRecord[] = [
  {
    id: "MT-6101",
    roomName: "Pool Villa 1",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    issueCategory: "HVAC",
    workOrderType: "Guest Reported",
    maintenanceStatus: "In Progress",
    severity: "High",
    roomImpact: "Limited",
    assignedTo: "Joel Ramirez",
    dueWindow: "Before 3:00 PM",
    blocker: "Compressor test still running",
    reportedBy: "Front Desk",
    lastUpdated: "6 mins ago",
    priority: true,
  },
  {
    id: "MT-6102",
    roomName: "Family Villa 2",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    issueCategory: "Furniture",
    workOrderType: "Turnover Repair",
    maintenanceStatus: "For Verification",
    severity: "Medium",
    roomImpact: "Sellable",
    assignedTo: "Leo Santos",
    dueWindow: "Before 1:30 PM",
    blocker: "Supervisor signoff pending",
    reportedBy: "Housekeeping",
    lastUpdated: "14 mins ago",
    priority: false,
  },
  {
    id: "MT-6103",
    roomName: "Garden Suite 4",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    issueCategory: "Plumbing",
    workOrderType: "Guest Reported",
    maintenanceStatus: "Open",
    severity: "Medium",
    roomImpact: "Limited",
    assignedTo: "Raffy Dizon",
    dueWindow: "Before 4:00 PM",
    blocker: "Awaiting room access window",
    reportedBy: "Front Desk",
    lastUpdated: "21 mins ago",
    priority: true,
  },
  {
    id: "MT-6104",
    roomName: "Casita 8",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    issueCategory: "Electrical",
    workOrderType: "Turnover Repair",
    maintenanceStatus: "Awaiting Parts",
    severity: "Critical",
    roomImpact: "Out of Order",
    assignedTo: "Paolo Reyes",
    dueWindow: "Part ETA 5:30 PM",
    blocker: "Breaker replacement not yet delivered",
    reportedBy: "Housekeeping",
    lastUpdated: "28 mins ago",
    priority: true,
  },
  {
    id: "MT-6105",
    roomName: "Verde Villa 3",
    resortName: "Casa Verde Private Villas",
    tenantName: "Casa Verde Leisure",
    issueCategory: "General Repair",
    workOrderType: "Preventive",
    maintenanceStatus: "Resolved",
    severity: "Low",
    roomImpact: "Sellable",
    assignedTo: "Mico Alvarez",
    dueWindow: "Closed at 10:20 AM",
    blocker: "No active blocker",
    reportedBy: "Engineering",
    lastUpdated: "11 mins ago",
    priority: false,
  },
  {
    id: "MT-6106",
    roomName: "Isla Deluxe 2",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    issueCategory: "Plumbing",
    workOrderType: "Guest Reported",
    maintenanceStatus: "In Progress",
    severity: "High",
    roomImpact: "Limited",
    assignedTo: "Arvin Flores",
    dueWindow: "Before 2:15 PM",
    blocker: "Leak isolation ongoing",
    reportedBy: "Front Desk",
    lastUpdated: "8 mins ago",
    priority: true,
  },
  {
    id: "MT-6107",
    roomName: "Reef Suite 6",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    issueCategory: "HVAC",
    workOrderType: "Preventive",
    maintenanceStatus: "For Verification",
    severity: "Low",
    roomImpact: "Sellable",
    assignedTo: "Emil Gutierrez",
    dueWindow: "Before 12:45 PM",
    blocker: "Temperature validation pending",
    reportedBy: "Engineering",
    lastUpdated: "17 mins ago",
    priority: false,
  },
  {
    id: "MT-6108",
    roomName: "Coral Family 1",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    issueCategory: "Furniture",
    workOrderType: "Turnover Repair",
    maintenanceStatus: "Open",
    severity: "Medium",
    roomImpact: "Limited",
    assignedTo: "Emil Gutierrez",
    dueWindow: "Before 3:30 PM",
    blocker: "Replacement headboard not staged",
    reportedBy: "Housekeeping",
    lastUpdated: "23 mins ago",
    priority: false,
  },
  {
    id: "MT-6109",
    roomName: "Bayfront Suite 5",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    issueCategory: "General Repair",
    workOrderType: "Facility Check",
    maintenanceStatus: "Resolved",
    severity: "Low",
    roomImpact: "Sellable",
    assignedTo: "Noel Castro",
    dueWindow: "Closed at 9:50 AM",
    blocker: "No active blocker",
    reportedBy: "Engineering",
    lastUpdated: "19 mins ago",
    priority: false,
  },
  {
    id: "MT-6110",
    roomName: "Peak Villa 2",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    issueCategory: "Electrical",
    workOrderType: "Guest Reported",
    maintenanceStatus: "Awaiting Parts",
    severity: "Critical",
    roomImpact: "Out of Order",
    assignedTo: "Benjie Torres",
    dueWindow: "Part ETA 6:00 PM",
    blocker: "Lighting control board on order",
    reportedBy: "Front Desk",
    lastUpdated: "32 mins ago",
    priority: true,
  },
];
