export type NotificationRecord = {
  id: string;
  notificationTitle: string;
  resortName: string;
  tenantName: string;
  category:
    | "Reservation Alert"
    | "System Notice"
    | "Billing Reminder"
    | "Operations Update"
    | "Promotional Broadcast";
  audienceType: "Guest" | "Tenant Staff" | "Owners" | "All Users";
  channel: "Email" | "SMS" | "Push" | "In-App";
  deliveryStatus: "Draft" | "Queued" | "Sent" | "Failed" | "Needs Review";
  priorityLevel: "Normal" | "Watch" | "Urgent";
  deliveryWindow: string;
  sentBy: string;
  note: string;
  lastUpdated: string;
  priority: boolean;
};

export const notificationRecords: NotificationRecord[] = [
  {
    id: "NTF-1201",
    notificationTitle: "Arrival Reminder Batch",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    category: "Reservation Alert",
    audienceType: "Guest",
    channel: "SMS",
    deliveryStatus: "Queued",
    priorityLevel: "Urgent",
    deliveryWindow: "Scheduled for 1:00 PM",
    sentBy: "Mika Dela Cruz",
    note: "Early check-in details still need final merge tags before release.",
    lastUpdated: "5 mins ago",
    priority: true,
  },
  {
    id: "NTF-1202",
    notificationTitle: "Azure OTA Sync Advisory",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    category: "System Notice",
    audienceType: "Tenant Staff",
    channel: "In-App",
    deliveryStatus: "Sent",
    priorityLevel: "Watch",
    deliveryWindow: "Released at 10:45 AM",
    sentBy: "Liza Ong",
    note: "Delivery completed after inventory sync delay warning was published.",
    lastUpdated: "14 mins ago",
    priority: false,
  },
  {
    id: "NTF-1203",
    notificationTitle: "Owner Payout Reminder",
    resortName: "Casa Verde Private Villas",
    tenantName: "Casa Verde Leisure",
    category: "Billing Reminder",
    audienceType: "Owners",
    channel: "Email",
    deliveryStatus: "Needs Review",
    priorityLevel: "Watch",
    deliveryWindow: "Approval due before 3:00 PM",
    sentBy: "Mira Valdez",
    note: "Owner summary attachment still needs updated figures from finance.",
    lastUpdated: "18 mins ago",
    priority: true,
  },
  {
    id: "NTF-1204",
    notificationTitle: "Blue Reef Maintenance Update",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    category: "Operations Update",
    audienceType: "Tenant Staff",
    channel: "Push",
    deliveryStatus: "Failed",
    priorityLevel: "Urgent",
    deliveryWindow: "Retry needed now",
    sentBy: "Janine Castro",
    note: "Push batch failed because two device groups were not resolved correctly.",
    lastUpdated: "7 mins ago",
    priority: true,
  },
  {
    id: "NTF-1205",
    notificationTitle: "Coral Peak Promo Flash Sale",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    category: "Promotional Broadcast",
    audienceType: "All Users",
    channel: "Email",
    deliveryStatus: "Draft",
    priorityLevel: "Normal",
    deliveryWindow: "Pending campaign approval",
    sentBy: "Mina Torres",
    note: "Creative headline and room rate blocks are still under marketing review.",
    lastUpdated: "21 mins ago",
    priority: false,
  },
  {
    id: "NTF-1206",
    notificationTitle: "Bayfront Checkout Notice",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    category: "Reservation Alert",
    audienceType: "Guest",
    channel: "In-App",
    deliveryStatus: "Sent",
    priorityLevel: "Normal",
    deliveryWindow: "Released at 11:10 AM",
    sentBy: "Noel Ramos",
    note: "Checkout guidance and transport reminder were pushed successfully.",
    lastUpdated: "11 mins ago",
    priority: false,
  },
  {
    id: "NTF-1207",
    notificationTitle: "Isla Finance Export Advisory",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    category: "System Notice",
    audienceType: "Tenant Staff",
    channel: "Email",
    deliveryStatus: "Queued",
    priorityLevel: "Watch",
    deliveryWindow: "Scheduled for 2:15 PM",
    sentBy: "Rica Flores",
    note: "Finance team requested a tenant-wide advisory before report regeneration.",
    lastUpdated: "15 mins ago",
    priority: false,
  },
  {
    id: "NTF-1208",
    notificationTitle: "Peak Wellness Lead Nurture",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    category: "Promotional Broadcast",
    audienceType: "Guest",
    channel: "SMS",
    deliveryStatus: "Needs Review",
    priorityLevel: "Watch",
    deliveryWindow: "Approval due before 1:45 PM",
    sentBy: "Mina Torres",
    note: "Consent segment needs final validation before outbound marketing send.",
    lastUpdated: "9 mins ago",
    priority: true,
  },
  {
    id: "NTF-1209",
    notificationTitle: "Azure Anniversary Dinner Confirmed",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    category: "Operations Update",
    audienceType: "Tenant Staff",
    channel: "Push",
    deliveryStatus: "Sent",
    priorityLevel: "Normal",
    deliveryWindow: "Released at 10:20 AM",
    sentBy: "Paula Ramos",
    note: "Guest experience and F&B teams were both notified successfully.",
    lastUpdated: "20 mins ago",
    priority: false,
  },
  {
    id: "NTF-1210",
    notificationTitle: "Wave Hall Event Confirmation",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    category: "Reservation Alert",
    audienceType: "Lead",
    channel: "Email",
    deliveryStatus: "Draft",
    priorityLevel: "Urgent",
    deliveryWindow: "Must release before 4:00 PM",
    sentBy: "Janine Castro",
    note: "Final contract note is still missing AV inclusions for the client confirmation mail.",
    lastUpdated: "6 mins ago",
    priority: true,
  },
];
