export type PaymentIntegrationRecord = {
  id: string;
  providerName: string;
  category: "E-Wallet" | "Online Banking" | "Credit/Debit Card" | "Bank Transfer";
  accountName: string;
  accountNumber: string;
  expiryDate?: string;
  cvc?: string;
  integrationStatus: "Active" | "Review" | "Sandbox" | "Paused";
  webhookHealth: "Healthy" | "Watch" | "Failing";
  transactionVolume: number;
  settlementWindow: string;
  feeModel: string;
  supportedTenants: number;
  assignedTo: string;
  lastUpdated: string;
  note: string;
  priority: boolean;
};

export const paymentIntegrationRecords: PaymentIntegrationRecord[] = [
  {
    id: "PM-7101",
    providerName: "GCash",
    category: "E-Wallet",
    accountName: "Alrio Platform Wallet",
    accountNumber: "09171234567",
    integrationStatus: "Active",
    webhookHealth: "Healthy",
    transactionVolume: 482000,
    settlementWindow: "T+1 settlement",
    feeModel: "2.5% per successful payment",
    supportedTenants: 24,
    assignedTo: "Kara Mendoza",
    lastUpdated: "8 mins ago",
    note: "Primary e-wallet channel for resort guest payments and subscription checkout.",
    priority: false,
  },
  {
    id: "PM-7102",
    providerName: "Maya",
    category: "E-Wallet",
    accountName: "Alrio Maya Collection",
    accountNumber: "09179876543",
    integrationStatus: "Review",
    webhookHealth: "Watch",
    transactionVolume: 216000,
    settlementWindow: "T+1 settlement",
    feeModel: "2.2% standard wallet fee",
    supportedTenants: 17,
    assignedTo: "Liza Ong",
    lastUpdated: "12 mins ago",
    note: "Webhook retry delays are affecting some confirmation callbacks today.",
    priority: true,
  },
  {
    id: "PM-7103",
    providerName: "BPI Online",
    category: "Online Banking",
    accountName: "Alrio Resort Systems Inc.",
    accountNumber: "003412345678",
    integrationStatus: "Active",
    webhookHealth: "Healthy",
    transactionVolume: 351000,
    settlementWindow: "T+1 banking file",
    feeModel: "Flat PHP 25 per transfer",
    supportedTenants: 14,
    assignedTo: "Mira Valdez",
    lastUpdated: "15 mins ago",
    note: "Online banking option used mostly by enterprise tenants and manual settlements.",
    priority: false,
  },
  {
    id: "PM-7104",
    providerName: "BDO Pay",
    category: "Online Banking",
    accountName: "Alrio BDO Sandbox",
    accountNumber: "001100998877",
    integrationStatus: "Sandbox",
    webhookHealth: "Healthy",
    transactionVolume: 0,
    settlementWindow: "Sandbox only",
    feeModel: "Pending commercial pricing",
    supportedTenants: 0,
    assignedTo: "Noel Ramos",
    lastUpdated: "21 mins ago",
    note: "Still in certification before tenant rollout.",
    priority: false,
  },
  {
    id: "PM-7105",
    providerName: "Stripe Cards",
    category: "Credit/Debit Card",
    accountName: "Alrio Platform Cards",
    accountNumber: "4242424242424242",
    expiryDate: "12/28",
    cvc: "123",
    integrationStatus: "Active",
    webhookHealth: "Healthy",
    transactionVolume: 689000,
    settlementWindow: "Rolling 2-day payout",
    feeModel: "3.5% + fixed card fee",
    supportedTenants: 29,
    assignedTo: "Janine Castro",
    lastUpdated: "6 mins ago",
    note: "Main card processor for recurring subscription and direct tenant billing.",
    priority: false,
  },
  {
    id: "PM-7106",
    providerName: "PayMongo Cards",
    category: "Credit/Debit Card",
    accountName: "Alrio PayMongo Cards",
    accountNumber: "5555555555554444",
    expiryDate: "09/27",
    cvc: "456",
    integrationStatus: "Review",
    webhookHealth: "Failing",
    transactionVolume: 174000,
    settlementWindow: "T+2 payout",
    feeModel: "3.3% local card fee",
    supportedTenants: 11,
    assignedTo: "Mina Torres",
    lastUpdated: "4 mins ago",
    note: "Webhook signatures failed after last credentials rotation and needs immediate review.",
    priority: true,
  },
  {
    id: "PM-7107",
    providerName: "RCBC Transfer",
    category: "Bank Transfer",
    accountName: "Alrio Settlement Account",
    accountNumber: "065100023450",
    integrationStatus: "Active",
    webhookHealth: "Watch",
    transactionVolume: 203000,
    settlementWindow: "Same-day advisory",
    feeModel: "Manual transfer confirmation flow",
    supportedTenants: 9,
    assignedTo: "Aira Santos",
    lastUpdated: "19 mins ago",
    note: "Still relies on statement matching for some manual collections.",
    priority: false,
  },
  {
    id: "PM-7108",
    providerName: "UnionBank BizPay",
    category: "Bank Transfer",
    accountName: "Alrio UB BizPay",
    accountNumber: "001234567890",
    integrationStatus: "Paused",
    webhookHealth: "Watch",
    transactionVolume: 62000,
    settlementWindow: "Paused while credentials refresh",
    feeModel: "Enterprise transfer pricing",
    supportedTenants: 4,
    assignedTo: "Cleo Rivera",
    lastUpdated: "28 mins ago",
    note: "Temporarily paused while production keys are being reissued.",
    priority: true,
  },
];
