export type TenantClient = {
  id: string;
  tenantName: string;
  ownerName: string;
  ownerEmail: string;
  plan: "Trial" | "Starter" | "Growth" | "Enterprise";
  status: "Active" | "Trial" | "At Risk" | "Suspended";
  properties: number;
  activeStaff: number;
  monthlyRevenue: number;
  location: string;
  lastActivity: string;
  priority: boolean;
};

export const tenantClients: TenantClient[] = [
  {
    id: "TEN-1001",
    tenantName: "Alrio Hospitality Group",
    ownerName: "Kyle Andre Lim",
    ownerEmail: "kyle@alrioresort.com",
    plan: "Enterprise",
    status: "Active",
    properties: 3,
    activeStaff: 27,
    monthlyRevenue: 42000,
    location: "Batangas",
    lastActivity: "5 mins ago",
    priority: true,
  },
  {
    id: "TEN-1002",
    tenantName: "Azure Palms Hospitality",
    ownerName: "Marian Reyes",
    ownerEmail: "marian@azurepalms.ph",
    plan: "Growth",
    status: "Active",
    properties: 2,
    activeStaff: 18,
    monthlyRevenue: 28000,
    location: "Laguna",
    lastActivity: "18 mins ago",
    priority: false,
  },
  {
    id: "TEN-1003",
    tenantName: "Casa Verde Leisure",
    ownerName: "Paolo Cruz",
    ownerEmail: "paolo@casaverde.ph",
    plan: "Growth",
    status: "Active",
    properties: 2,
    activeStaff: 14,
    monthlyRevenue: 24000,
    location: "Quezon",
    lastActivity: "26 mins ago",
    priority: false,
  },
  {
    id: "TEN-1004",
    tenantName: "Harbor Mist Ventures",
    ownerName: "Mika Santiago",
    ownerEmail: "mika@harbormist.ph",
    plan: "Starter",
    status: "At Risk",
    properties: 1,
    activeStaff: 8,
    monthlyRevenue: 9000,
    location: "Zambales",
    lastActivity: "1 hr ago",
    priority: true,
  },
  {
    id: "TEN-1005",
    tenantName: "Isla Jardin Retreats",
    ownerName: "Rina Torres",
    ownerEmail: "rina@islajardin.ph",
    plan: "Growth",
    status: "Active",
    properties: 2,
    activeStaff: 11,
    monthlyRevenue: 21000,
    location: "Palawan",
    lastActivity: "11 mins ago",
    priority: false,
  },
  {
    id: "TEN-1006",
    tenantName: "Sunridge Coves",
    ownerName: "Anton Lim",
    ownerEmail: "anton@sunridge.ph",
    plan: "Trial",
    status: "Trial",
    properties: 1,
    activeStaff: 5,
    monthlyRevenue: 0,
    location: "Cavite",
    lastActivity: "37 mins ago",
    priority: false,
  },
  {
    id: "TEN-1007",
    tenantName: "Coco Haven Stay",
    ownerName: "Bianca David",
    ownerEmail: "bianca@cocohaven.ph",
    plan: "Starter",
    status: "Active",
    properties: 1,
    activeStaff: 6,
    monthlyRevenue: 8500,
    location: "Bataan",
    lastActivity: "48 mins ago",
    priority: false,
  },
  {
    id: "TEN-1008",
    tenantName: "Blue Reef Escapes",
    ownerName: "Jericho Sy",
    ownerEmail: "jericho@bluereef.ph",
    plan: "Enterprise",
    status: "Active",
    properties: 4,
    activeStaff: 33,
    monthlyRevenue: 51000,
    location: "Cebu",
    lastActivity: "3 mins ago",
    priority: true,
  },
  {
    id: "TEN-1009",
    tenantName: "Luna Coast Suites",
    ownerName: "Trisha Gamboa",
    ownerEmail: "trisha@lunacoast.ph",
    plan: "Trial",
    status: "Trial",
    properties: 1,
    activeStaff: 4,
    monthlyRevenue: 0,
    location: "La Union",
    lastActivity: "2 hrs ago",
    priority: false,
  },
  {
    id: "TEN-1010",
    tenantName: "Greenwater Villas",
    ownerName: "Harvey Ramos",
    ownerEmail: "harvey@greenwater.ph",
    plan: "Starter",
    status: "Suspended",
    properties: 1,
    activeStaff: 0,
    monthlyRevenue: 6500,
    location: "Rizal",
    lastActivity: "3 days ago",
    priority: false,
  },
  {
    id: "TEN-1011",
    tenantName: "Bayfront Hideaway",
    ownerName: "Angela Yap",
    ownerEmail: "angela@bayfront.ph",
    plan: "Growth",
    status: "Active",
    properties: 2,
    activeStaff: 13,
    monthlyRevenue: 23000,
    location: "Subic",
    lastActivity: "16 mins ago",
    priority: false,
  },
  {
    id: "TEN-1012",
    tenantName: "Coral Peak Resorts",
    ownerName: "Nico Velasco",
    ownerEmail: "nico@coralpeak.ph",
    plan: "Enterprise",
    status: "At Risk",
    properties: 3,
    activeStaff: 20,
    monthlyRevenue: 39000,
    location: "Davao",
    lastActivity: "57 mins ago",
    priority: true,
  },
];
