export type ResortRecord = {
  id: string;
  resortName: string;
  tenantName: string;
  ownerName: string;
  location: string;
  units: number;
  occupancyRate: number;
  activeBookings: number;
  monthlyRevenue: number;
  operationsStatus: "Stable" | "Busy" | "Attention";
  setupStatus: "Live" | "Launching" | "Needs Review";
  channelStatus: "Connected" | "Partial" | "Offline";
  supportTier: "Standard" | "Priority" | "Dedicated";
  lastSync: string;
  priority: boolean;
};

export const resortRecords: ResortRecord[] = [
  {
    id: "RST-2001",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    ownerName: "Kyle Andre Lim",
    location: "Batangas",
    units: 18,
    occupancyRate: 91,
    activeBookings: 24,
    monthlyRevenue: 1240000,
    operationsStatus: "Busy",
    setupStatus: "Live",
    channelStatus: "Connected",
    supportTier: "Dedicated",
    lastSync: "3 mins ago",
    priority: true,
  },
  {
    id: "RST-2002",
    resortName: "Alrio Ridge Villas",
    tenantName: "Alrio Hospitality Group",
    ownerName: "Kyle Andre Lim",
    location: "Tagaytay",
    units: 10,
    occupancyRate: 76,
    activeBookings: 12,
    monthlyRevenue: 468000,
    operationsStatus: "Stable",
    setupStatus: "Live",
    channelStatus: "Connected",
    supportTier: "Dedicated",
    lastSync: "14 mins ago",
    priority: false,
  },
  {
    id: "RST-2003",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    ownerName: "Marian Reyes",
    location: "Laguna",
    units: 14,
    occupancyRate: 84,
    activeBookings: 17,
    monthlyRevenue: 924000,
    operationsStatus: "Stable",
    setupStatus: "Live",
    channelStatus: "Connected",
    supportTier: "Priority",
    lastSync: "11 mins ago",
    priority: false,
  },
  {
    id: "RST-2004",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    ownerName: "Marian Reyes",
    location: "Laguna",
    units: 8,
    occupancyRate: 69,
    activeBookings: 7,
    monthlyRevenue: 312000,
    operationsStatus: "Attention",
    setupStatus: "Needs Review",
    channelStatus: "Partial",
    supportTier: "Priority",
    lastSync: "1 hr ago",
    priority: true,
  },
  {
    id: "RST-2005",
    resortName: "Casa Verde Private Villas",
    tenantName: "Casa Verde Leisure",
    ownerName: "Paolo Cruz",
    location: "Quezon",
    units: 11,
    occupancyRate: 79,
    activeBookings: 13,
    monthlyRevenue: 818000,
    operationsStatus: "Stable",
    setupStatus: "Live",
    channelStatus: "Connected",
    supportTier: "Priority",
    lastSync: "20 mins ago",
    priority: false,
  },
  {
    id: "RST-2006",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    ownerName: "Rina Torres",
    location: "Palawan",
    units: 9,
    occupancyRate: 73,
    activeBookings: 9,
    monthlyRevenue: 472000,
    operationsStatus: "Stable",
    setupStatus: "Live",
    channelStatus: "Partial",
    supportTier: "Priority",
    lastSync: "28 mins ago",
    priority: false,
  },
  {
    id: "RST-2007",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    ownerName: "Jericho Sy",
    location: "Cebu",
    units: 22,
    occupancyRate: 88,
    activeBookings: 29,
    monthlyRevenue: 1375000,
    operationsStatus: "Busy",
    setupStatus: "Live",
    channelStatus: "Connected",
    supportTier: "Dedicated",
    lastSync: "5 mins ago",
    priority: true,
  },
  {
    id: "RST-2008",
    resortName: "Blue Reef Garden Wing",
    tenantName: "Blue Reef Escapes",
    ownerName: "Jericho Sy",
    location: "Cebu",
    units: 12,
    occupancyRate: 64,
    activeBookings: 8,
    monthlyRevenue: 356000,
    operationsStatus: "Attention",
    setupStatus: "Launching",
    channelStatus: "Partial",
    supportTier: "Dedicated",
    lastSync: "42 mins ago",
    priority: true,
  },
  {
    id: "RST-2009",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    ownerName: "Angela Yap",
    location: "Subic",
    units: 13,
    occupancyRate: 81,
    activeBookings: 15,
    monthlyRevenue: 539000,
    operationsStatus: "Stable",
    setupStatus: "Live",
    channelStatus: "Connected",
    supportTier: "Priority",
    lastSync: "17 mins ago",
    priority: false,
  },
  {
    id: "RST-2010",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    ownerName: "Nico Velasco",
    location: "Davao",
    units: 16,
    occupancyRate: 67,
    activeBookings: 10,
    monthlyRevenue: 602000,
    operationsStatus: "Attention",
    setupStatus: "Needs Review",
    channelStatus: "Offline",
    supportTier: "Dedicated",
    lastSync: "2 hrs ago",
    priority: true,
  },
];
