export type RoomRecord = {
  id: string;
  roomName: string;
  resortName: string;
  tenantName: string;
  category: "Villa" | "Suite" | "Casita" | "Family Room" | "Deluxe Room";
  capacity: number;
  rate: number;
  occupancyStatus: "Occupied" | "Vacant" | "Reserved";
  housekeepingStatus: "Ready" | "Cleaning" | "Inspection";
  maintenanceStatus: "Clear" | "Watch" | "Issue";
  bookingWindow: string;
  floorOrZone: string;
  lastUpdated: string;
  priority: boolean;
};

export const roomRecords: RoomRecord[] = [
  {
    id: "RM-3001",
    roomName: "Family Villa 2",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    category: "Villa",
    capacity: 6,
    rate: 12800,
    occupancyStatus: "Occupied",
    housekeepingStatus: "Ready",
    maintenanceStatus: "Clear",
    bookingWindow: "Until Apr 22",
    floorOrZone: "Garden Wing",
    lastUpdated: "4 mins ago",
    priority: true,
  },
  {
    id: "RM-3002",
    roomName: "Pool Villa 1",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    category: "Villa",
    capacity: 4,
    rate: 16200,
    occupancyStatus: "Reserved",
    housekeepingStatus: "Inspection",
    maintenanceStatus: "Watch",
    bookingWindow: "Apr 20 arrival",
    floorOrZone: "Pool Deck",
    lastUpdated: "11 mins ago",
    priority: true,
  },
  {
    id: "RM-3003",
    roomName: "Garden Suite 4",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    category: "Suite",
    capacity: 3,
    rate: 8950,
    occupancyStatus: "Occupied",
    housekeepingStatus: "Ready",
    maintenanceStatus: "Clear",
    bookingWindow: "Until Apr 21",
    floorOrZone: "North Block",
    lastUpdated: "16 mins ago",
    priority: false,
  },
  {
    id: "RM-3004",
    roomName: "Casita 8",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    category: "Casita",
    capacity: 2,
    rate: 5800,
    occupancyStatus: "Vacant",
    housekeepingStatus: "Cleaning",
    maintenanceStatus: "Issue",
    bookingWindow: "Blocked today",
    floorOrZone: "Cliffside Row",
    lastUpdated: "27 mins ago",
    priority: true,
  },
  {
    id: "RM-3005",
    roomName: "Verde Villa 3",
    resortName: "Casa Verde Private Villas",
    tenantName: "Casa Verde Leisure",
    category: "Villa",
    capacity: 5,
    rate: 11600,
    occupancyStatus: "Reserved",
    housekeepingStatus: "Inspection",
    maintenanceStatus: "Clear",
    bookingWindow: "Apr 20 arrival",
    floorOrZone: "Palm Court",
    lastUpdated: "22 mins ago",
    priority: false,
  },
  {
    id: "RM-3006",
    roomName: "Isla Deluxe 2",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    category: "Deluxe Room",
    capacity: 2,
    rate: 6400,
    occupancyStatus: "Vacant",
    housekeepingStatus: "Ready",
    maintenanceStatus: "Clear",
    bookingWindow: "Open this week",
    floorOrZone: "Main Lodge",
    lastUpdated: "35 mins ago",
    priority: false,
  },
  {
    id: "RM-3007",
    roomName: "Reef Suite 6",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    category: "Suite",
    capacity: 3,
    rate: 9800,
    occupancyStatus: "Occupied",
    housekeepingStatus: "Ready",
    maintenanceStatus: "Clear",
    bookingWindow: "Until Apr 23",
    floorOrZone: "Reef Tower",
    lastUpdated: "8 mins ago",
    priority: false,
  },
  {
    id: "RM-3008",
    roomName: "Coral Family 1",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    category: "Family Room",
    capacity: 5,
    rate: 11200,
    occupancyStatus: "Reserved",
    housekeepingStatus: "Cleaning",
    maintenanceStatus: "Watch",
    bookingWindow: "Apr 21 arrival",
    floorOrZone: "Family Hall",
    lastUpdated: "19 mins ago",
    priority: true,
  },
  {
    id: "RM-3009",
    roomName: "Bayfront Suite 5",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    category: "Suite",
    capacity: 2,
    rate: 7600,
    occupancyStatus: "Occupied",
    housekeepingStatus: "Ready",
    maintenanceStatus: "Clear",
    bookingWindow: "Until Apr 20",
    floorOrZone: "Ocean Wing",
    lastUpdated: "12 mins ago",
    priority: false,
  },
  {
    id: "RM-3010",
    roomName: "Peak Villa 2",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    category: "Villa",
    capacity: 4,
    rate: 13400,
    occupancyStatus: "Vacant",
    housekeepingStatus: "Inspection",
    maintenanceStatus: "Issue",
    bookingWindow: "Offline today",
    floorOrZone: "Ridge Deck",
    lastUpdated: "1 hr ago",
    priority: true,
  },
];
