export type BillingRecord = {
  id: string;
  tenantName: string;
  resortName: string;
  planName: "Starter" | "Growth" | "Enterprise";
  billingCycle: "Monthly" | "Annual";
  invoiceStatus: "Draft" | "Issued" | "Due Soon" | "Overdue" | "Paid";
  collectionStatus: "Clear" | "Watch" | "Escalated";
  amountDue: number;
  nextBillDate: string;
  lastPaymentDate: string;
  paymentMethod: "Card" | "Bank Transfer" | "Auto Debit";
  assignedTo: string;
  note: string;
  priority: boolean;
};

export const billingRecords: BillingRecord[] = [
  {
    id: "BL-2401",
    tenantName: "Alrio Hospitality Group",
    resortName: "Alrio Resort Batangas",
    planName: "Enterprise",
    billingCycle: "Annual",
    invoiceStatus: "Due Soon",
    collectionStatus: "Watch",
    amountDue: 95880,
    nextBillDate: "Apr 30, 2026",
    lastPaymentDate: "Apr 30, 2025",
    paymentMethod: "Bank Transfer",
    assignedTo: "Kara Mendoza",
    note: "Annual renewal is queued and waiting for purchase-order confirmation.",
    priority: true,
  },
  {
    id: "BL-2402",
    tenantName: "Azure Palms Hospitality",
    resortName: "Azure Palms Resort",
    planName: "Growth",
    billingCycle: "Monthly",
    invoiceStatus: "Overdue",
    collectionStatus: "Escalated",
    amountDue: 5999,
    nextBillDate: "Apr 22, 2026",
    lastPaymentDate: "Mar 22, 2026",
    paymentMethod: "Card",
    assignedTo: "Liza Ong",
    note: "Primary card failed twice and collection follow-up is already active.",
    priority: true,
  },
  {
    id: "BL-2403",
    tenantName: "Casa Verde Leisure",
    resortName: "Casa Verde Private Villas",
    planName: "Growth",
    billingCycle: "Monthly",
    invoiceStatus: "Issued",
    collectionStatus: "Clear",
    amountDue: 5999,
    nextBillDate: "May 02, 2026",
    lastPaymentDate: "Apr 02, 2026",
    paymentMethod: "Auto Debit",
    assignedTo: "Mira Valdez",
    note: "Invoice generated on schedule and auto-debit is expected on due date.",
    priority: false,
  },
  {
    id: "BL-2404",
    tenantName: "Blue Reef Escapes",
    resortName: "Blue Reef Escapes",
    planName: "Starter",
    billingCycle: "Monthly",
    invoiceStatus: "Paid",
    collectionStatus: "Clear",
    amountDue: 2499,
    nextBillDate: "May 05, 2026",
    lastPaymentDate: "Apr 05, 2026",
    paymentMethod: "Card",
    assignedTo: "Janine Castro",
    note: "Tenant is current and no billing exceptions are open this cycle.",
    priority: false,
  },
  {
    id: "BL-2405",
    tenantName: "Coral Peak Resorts",
    resortName: "Coral Peak Resorts",
    planName: "Enterprise",
    billingCycle: "Annual",
    invoiceStatus: "Issued",
    collectionStatus: "Watch",
    amountDue: 124680,
    nextBillDate: "May 10, 2026",
    lastPaymentDate: "May 10, 2025",
    paymentMethod: "Bank Transfer",
    assignedTo: "Mina Torres",
    note: "Annual invoice is out and procurement requested an updated billing memo.",
    priority: true,
  },
  {
    id: "BL-2406",
    tenantName: "Bayfront Hideaway",
    resortName: "Bayfront Hideaway",
    planName: "Starter",
    billingCycle: "Monthly",
    invoiceStatus: "Overdue",
    collectionStatus: "Escalated",
    amountDue: 2499,
    nextBillDate: "Apr 18, 2026",
    lastPaymentDate: "Mar 18, 2026",
    paymentMethod: "Card",
    assignedTo: "Noel Ramos",
    note: "Billing is paused pending confirmation of updated card credentials.",
    priority: true,
  },
  {
    id: "BL-2407",
    tenantName: "Isla Jardin Retreats",
    resortName: "Isla Jardin Suites",
    planName: "Growth",
    billingCycle: "Annual",
    invoiceStatus: "Paid",
    collectionStatus: "Clear",
    amountDue: 71988,
    nextBillDate: "Jan 14, 2027",
    lastPaymentDate: "Jan 14, 2026",
    paymentMethod: "Auto Debit",
    assignedTo: "Rica Flores",
    note: "Annual subscription already settled and locked for the current term.",
    priority: false,
  },
  {
    id: "BL-2408",
    tenantName: "Peak Wellness Collection",
    resortName: "Peak Wellness Suites",
    planName: "Growth",
    billingCycle: "Monthly",
    invoiceStatus: "Due Soon",
    collectionStatus: "Watch",
    amountDue: 5999,
    nextBillDate: "Apr 29, 2026",
    lastPaymentDate: "Mar 29, 2026",
    paymentMethod: "Bank Transfer",
    assignedTo: "Mina Torres",
    note: "Tenant requested manual remittance this cycle instead of card billing.",
    priority: false,
  },
  {
    id: "BL-2409",
    tenantName: "Suncrest Cove Hospitality",
    resortName: "Suncrest Cove Villas",
    planName: "Starter",
    billingCycle: "Monthly",
    invoiceStatus: "Draft",
    collectionStatus: "Clear",
    amountDue: 2499,
    nextBillDate: "May 03, 2026",
    lastPaymentDate: "Apr 03, 2026",
    paymentMethod: "Card",
    assignedTo: "Aira Santos",
    note: "Invoice draft is waiting on a mid-cycle add-on adjustment before release.",
    priority: false,
  },
  {
    id: "BL-2410",
    tenantName: "Verde Haven Resorts",
    resortName: "Verde Haven Residences",
    planName: "Enterprise",
    billingCycle: "Annual",
    invoiceStatus: "Issued",
    collectionStatus: "Watch",
    amountDue: 154800,
    nextBillDate: "May 15, 2026",
    lastPaymentDate: "May 15, 2025",
    paymentMethod: "Bank Transfer",
    assignedTo: "Cleo Rivera",
    note: "Multi-property annual invoice needs signoff from the tenant finance lead.",
    priority: true,
  },
];
