export type AmenitiesRecord = {
  id: string;
  amenityName: string;
  resortName: string;
  tenantName: string;
  amenityType:
    | "Pool"
    | "Spa"
    | "Restaurant"
    | "Function Hall"
    | "Activity Deck"
    | "Shuttle";
  operationalStatus: "Available" | "Limited" | "Reserved" | "Maintenance" | "Offline";
  staffingStatus: "Covered" | "Short Staff" | "Vendor Support";
  bookingWindow: string;
  guestDemand: "Low" | "Moderate" | "High" | "Peak";
  assignedLead: string;
  availabilityNote: string;
  serviceHours: string;
  lastUpdated: string;
  priority: boolean;
};

export const amenitiesRecords: AmenitiesRecord[] = [
  {
    id: "AM-7101",
    amenityName: "Infinity Pool Deck",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    amenityType: "Pool",
    operationalStatus: "Limited",
    staffingStatus: "Covered",
    bookingWindow: "Open until 8:00 PM",
    guestDemand: "Peak",
    assignedLead: "Marco Valdez",
    availabilityNote: "One pool zone closed for tile treatment",
    serviceHours: "8:00 AM - 8:00 PM",
    lastUpdated: "6 mins ago",
    priority: true,
  },
  {
    id: "AM-7102",
    amenityName: "Sea Breeze Spa",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    amenityType: "Spa",
    operationalStatus: "Reserved",
    staffingStatus: "Covered",
    bookingWindow: "Fully booked 1:00 PM - 5:00 PM",
    guestDemand: "High",
    assignedLead: "Tina Mercado",
    availabilityNote: "Walk-ins paused during premium treatment block",
    serviceHours: "10:00 AM - 9:00 PM",
    lastUpdated: "14 mins ago",
    priority: false,
  },
  {
    id: "AM-7103",
    amenityName: "Cliffside Grill",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    amenityType: "Restaurant",
    operationalStatus: "Available",
    staffingStatus: "Short Staff",
    bookingWindow: "Dinner service open",
    guestDemand: "High",
    assignedLead: "Pia Navarro",
    availabilityNote: "Reduced table turn due to one missing server",
    serviceHours: "11:00 AM - 10:00 PM",
    lastUpdated: "18 mins ago",
    priority: true,
  },
  {
    id: "AM-7104",
    amenityName: "Sunset Pavilion",
    resortName: "Casa Verde Private Villas",
    tenantName: "Casa Verde Leisure",
    amenityType: "Function Hall",
    operationalStatus: "Reserved",
    staffingStatus: "Vendor Support",
    bookingWindow: "Private event until 6:00 PM",
    guestDemand: "Moderate",
    assignedLead: "Ivy De Leon",
    availabilityNote: "Guest access limited during event setup and teardown",
    serviceHours: "9:00 AM - 10:00 PM",
    lastUpdated: "11 mins ago",
    priority: false,
  },
  {
    id: "AM-7105",
    amenityName: "Island Shuttle",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    amenityType: "Shuttle",
    operationalStatus: "Maintenance",
    staffingStatus: "Vendor Support",
    bookingWindow: "Next slot pending 3:30 PM release",
    guestDemand: "Moderate",
    assignedLead: "Aris Flores",
    availabilityNote: "Backup vehicle requested for airport pickups",
    serviceHours: "6:00 AM - 10:00 PM",
    lastUpdated: "21 mins ago",
    priority: true,
  },
  {
    id: "AM-7106",
    amenityName: "Coral Activity Deck",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    amenityType: "Activity Deck",
    operationalStatus: "Available",
    staffingStatus: "Covered",
    bookingWindow: "Open for dive briefing at 2:00 PM",
    guestDemand: "Moderate",
    assignedLead: "Jules Serrano",
    availabilityNote: "Equipment prep completed for afternoon group",
    serviceHours: "7:00 AM - 7:00 PM",
    lastUpdated: "8 mins ago",
    priority: false,
  },
  {
    id: "AM-7107",
    amenityName: "Lagoon Pool",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    amenityType: "Pool",
    operationalStatus: "Offline",
    staffingStatus: "Covered",
    bookingWindow: "Closed until water treatment clears",
    guestDemand: "High",
    assignedLead: "Neil Castro",
    availabilityNote: "Chemical balance is still outside safe threshold",
    serviceHours: "8:00 AM - 7:00 PM",
    lastUpdated: "27 mins ago",
    priority: true,
  },
  {
    id: "AM-7108",
    amenityName: "Peak Wellness Spa",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    amenityType: "Spa",
    operationalStatus: "Limited",
    staffingStatus: "Short Staff",
    bookingWindow: "Only 4 treatment slots left today",
    guestDemand: "Peak",
    assignedLead: "Mina Torres",
    availabilityNote: "Second therapist still on delayed shift arrival",
    serviceHours: "10:00 AM - 9:00 PM",
    lastUpdated: "16 mins ago",
    priority: true,
  },
  {
    id: "AM-7109",
    amenityName: "Harbor View Dining",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    amenityType: "Restaurant",
    operationalStatus: "Available",
    staffingStatus: "Covered",
    bookingWindow: "Lunch service open",
    guestDemand: "Moderate",
    assignedLead: "Noel Ramos",
    availabilityNote: "Normal dine-in and room service flow",
    serviceHours: "6:30 AM - 10:00 PM",
    lastUpdated: "10 mins ago",
    priority: false,
  },
  {
    id: "AM-7110",
    amenityName: "Wave Hall",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    amenityType: "Function Hall",
    operationalStatus: "Maintenance",
    staffingStatus: "Vendor Support",
    bookingWindow: "Blocked until 4:30 PM safety check",
    guestDemand: "Low",
    assignedLead: "Jules Serrano",
    availabilityNote: "Sound rigging inspection in progress",
    serviceHours: "9:00 AM - 11:00 PM",
    lastUpdated: "24 mins ago",
    priority: false,
  },
];
