export type ReviewRecord = {
  id: string;
  guestName: string;
  resortName: string;
  tenantName: string;
  sourcePlatform: "Google" | "Facebook" | "Tripadvisor" | "Booking.com" | "Direct";
  rating: 1 | 2 | 3 | 4 | 5;
  reviewStatus: "New" | "Responded" | "Pending Response" | "Escalated" | "Closed";
  sentimentLevel: "Positive" | "Mixed" | "Negative";
  reviewSummary: string;
  assignedTo: string;
  postedAt: string;
  recoveryNote: string;
  priority: boolean;
};

export const reviewRecords: ReviewRecord[] = [
  {
    id: "RVW-1401",
    guestName: "Andrea Santos",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    sourcePlatform: "Google",
    rating: 2,
    reviewStatus: "Pending Response",
    sentimentLevel: "Negative",
    reviewSummary: "Guest praised the villa but cited delayed airport pickup coordination.",
    assignedTo: "Mika Dela Cruz",
    postedAt: "32 mins ago",
    recoveryNote: "Transport manager asked to confirm corrective action before response is posted.",
    priority: true,
  },
  {
    id: "RVW-1402",
    guestName: "Claire Dizon",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    sourcePlatform: "Facebook",
    rating: 5,
    reviewStatus: "Responded",
    sentimentLevel: "Positive",
    reviewSummary: "Guest highlighted the spa team and sunset dining experience.",
    assignedTo: "Liza Ong",
    postedAt: "1 hr ago",
    recoveryNote: "Thank-you response already published with loyalty return offer.",
    priority: false,
  },
  {
    id: "RVW-1403",
    guestName: "Michael Lim",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    sourcePlatform: "Booking.com",
    rating: 3,
    reviewStatus: "New",
    sentimentLevel: "Mixed",
    reviewSummary: "Stay was comfortable but room turnover was slower than expected.",
    assignedTo: "Paula Ramos",
    postedAt: "18 mins ago",
    recoveryNote: "Operations lead asked for housekeeping timeline before public reply.",
    priority: false,
  },
  {
    id: "RVW-1404",
    guestName: "Blue Reef Corporate Team",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    sourcePlatform: "Tripadvisor",
    rating: 2,
    reviewStatus: "Escalated",
    sentimentLevel: "Negative",
    reviewSummary: "Client reported billing confusion and event AV setup issues.",
    assignedTo: "Janine Castro",
    postedAt: "45 mins ago",
    recoveryNote: "Finance and events teams are still consolidating final recovery offer.",
    priority: true,
  },
  {
    id: "RVW-1405",
    guestName: "Nica Gomez",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    sourcePlatform: "Google",
    rating: 4,
    reviewStatus: "Pending Response",
    sentimentLevel: "Mixed",
    reviewSummary: "Guest loved the view but noted spa booking slots were too limited.",
    assignedTo: "Mina Torres",
    postedAt: "27 mins ago",
    recoveryNote: "Marketing wants to include a return offer in the response.",
    priority: true,
  },
  {
    id: "RVW-1406",
    guestName: "Mara Ong",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    sourcePlatform: "Direct",
    rating: 5,
    reviewStatus: "Closed",
    sentimentLevel: "Positive",
    reviewSummary: "Guest appreciated the front desk support and late checkout handling.",
    assignedTo: "Noel Ramos",
    postedAt: "2 hrs ago",
    recoveryNote: "Review was acknowledged internally and routed to the team recognition list.",
    priority: false,
  },
  {
    id: "RVW-1407",
    guestName: "Rina Bautista",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    sourcePlatform: "Google",
    rating: 1,
    reviewStatus: "Escalated",
    sentimentLevel: "Negative",
    reviewSummary: "Guest cited shuttle delays and unclear billing at departure.",
    assignedTo: "Rica Flores",
    postedAt: "21 mins ago",
    recoveryNote: "General manager requested a private outreach before publishing the final response.",
    priority: true,
  },
  {
    id: "RVW-1408",
    guestName: "Jonas Velasco",
    resortName: "Casa Verde Private Villas",
    tenantName: "Casa Verde Leisure",
    sourcePlatform: "Facebook",
    rating: 4,
    reviewStatus: "New",
    sentimentLevel: "Positive",
    reviewSummary: "Guest enjoyed the villa stay and private pool but asked for better signage.",
    assignedTo: "Mira Valdez",
    postedAt: "39 mins ago",
    recoveryNote: "Feedback was shared with on-site guest experience for follow-up.",
    priority: false,
  },
  {
    id: "RVW-1409",
    guestName: "Peak Wellness Retreat Lead",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    sourcePlatform: "Tripadvisor",
    rating: 3,
    reviewStatus: "Pending Response",
    sentimentLevel: "Mixed",
    reviewSummary: "Lead praised the facilities but expected faster reply times from the sales desk.",
    assignedTo: "Mina Torres",
    postedAt: "13 mins ago",
    recoveryNote: "Sales manager is preparing a public response with a service recovery note.",
    priority: true,
  },
  {
    id: "RVW-1410",
    guestName: "Wave Hall Event Planner",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    sourcePlatform: "Booking.com",
    rating: 2,
    reviewStatus: "New",
    sentimentLevel: "Negative",
    reviewSummary: "Reviewer mentioned event confirmation delays and incomplete AV coordination.",
    assignedTo: "Janine Castro",
    postedAt: "9 mins ago",
    recoveryNote: "Events and communications teams still need one aligned public reply.",
    priority: true,
  },
];
