export type EmailSmsRecord = {
  id: string;
  campaignName: string;
  resortName: string;
  tenantName: string;
  channel: "Email" | "SMS";
  messageType:
    | "Arrival Reminder"
    | "Promotional Blast"
    | "Billing Notice"
    | "Booking Confirmation"
    | "Operations Advisory";
  audienceType: "Guests" | "Leads" | "Tenant Staff" | "Owners";
  sendStatus: "Draft" | "Queued" | "Scheduled" | "Sent" | "Failed" | "Needs Approval";
  priorityLevel: "Normal" | "Watch" | "Urgent";
  deliveryWindow: string;
  owner: string;
  note: string;
  lastUpdated: string;
  priority: boolean;
};

export const emailSmsRecords: EmailSmsRecord[] = [
  {
    id: "EMS-1301",
    campaignName: "Batangas Arrival Reminder",
    resortName: "Alrio Resort Batangas",
    tenantName: "Alrio Hospitality Group",
    channel: "SMS",
    messageType: "Arrival Reminder",
    audienceType: "Guests",
    sendStatus: "Queued",
    priorityLevel: "Urgent",
    deliveryWindow: "Scheduled for 1:15 PM",
    owner: "Mika Dela Cruz",
    note: "Pickup note merge field still needs final verification before batch send.",
    lastUpdated: "4 mins ago",
    priority: true,
  },
  {
    id: "EMS-1302",
    campaignName: "Azure Wedding Leads Follow-Up",
    resortName: "Azure Palms Resort",
    tenantName: "Azure Palms Hospitality",
    channel: "Email",
    messageType: "Promotional Blast",
    audienceType: "Leads",
    sendStatus: "Needs Approval",
    priorityLevel: "Watch",
    deliveryWindow: "Approval due before 2:00 PM",
    owner: "Liza Ong",
    note: "Updated package pricing was inserted and needs manager signoff.",
    lastUpdated: "12 mins ago",
    priority: true,
  },
  {
    id: "EMS-1303",
    campaignName: "Casa Verde Owner Payout Note",
    resortName: "Casa Verde Private Villas",
    tenantName: "Casa Verde Leisure",
    channel: "Email",
    messageType: "Billing Notice",
    audienceType: "Owners",
    sendStatus: "Draft",
    priorityLevel: "Normal",
    deliveryWindow: "Pending finance attachment",
    owner: "Mira Valdez",
    note: "Owner statement attachment still needs refreshed payout figures.",
    lastUpdated: "16 mins ago",
    priority: false,
  },
  {
    id: "EMS-1304",
    campaignName: "Blue Reef Overbooking Advisory",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    channel: "SMS",
    messageType: "Operations Advisory",
    audienceType: "Tenant Staff",
    sendStatus: "Failed",
    priorityLevel: "Urgent",
    deliveryWindow: "Retry immediately",
    owner: "Janine Castro",
    note: "SMS gateway rejected the batch because of unresolved staff contact segments.",
    lastUpdated: "6 mins ago",
    priority: true,
  },
  {
    id: "EMS-1305",
    campaignName: "Coral Peak Wellness Weekend",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    channel: "Email",
    messageType: "Promotional Blast",
    audienceType: "Leads",
    sendStatus: "Scheduled",
    priorityLevel: "Watch",
    deliveryWindow: "Scheduled for 3:30 PM",
    owner: "Mina Torres",
    note: "Segment is locked and waiting on final hero creative export.",
    lastUpdated: "10 mins ago",
    priority: true,
  },
  {
    id: "EMS-1306",
    campaignName: "Bayfront Checkout Confirmation",
    resortName: "Bayfront Hideaway",
    tenantName: "Bayfront Hideaway",
    channel: "SMS",
    messageType: "Booking Confirmation",
    audienceType: "Guests",
    sendStatus: "Sent",
    priorityLevel: "Normal",
    deliveryWindow: "Released at 11:05 AM",
    owner: "Noel Ramos",
    note: "Checkout confirmation and transport note were delivered successfully.",
    lastUpdated: "9 mins ago",
    priority: false,
  },
  {
    id: "EMS-1307",
    campaignName: "Isla OTA Export Notice",
    resortName: "Isla Jardin Suites",
    tenantName: "Isla Jardin Retreats",
    channel: "Email",
    messageType: "Operations Advisory",
    audienceType: "Tenant Staff",
    sendStatus: "Sent",
    priorityLevel: "Normal",
    deliveryWindow: "Released at 10:40 AM",
    owner: "Rica Flores",
    note: "Export advisory was sent before regeneration started.",
    lastUpdated: "13 mins ago",
    priority: false,
  },
  {
    id: "EMS-1308",
    campaignName: "Peak Executive Retreat Nurture",
    resortName: "Coral Peak Resorts",
    tenantName: "Coral Peak Resorts",
    channel: "Email",
    messageType: "Promotional Blast",
    audienceType: "Leads",
    sendStatus: "Needs Approval",
    priorityLevel: "Watch",
    deliveryWindow: "Approval due before 1:50 PM",
    owner: "Mina Torres",
    note: "Marketing wants one final review of executive perks and transport copy.",
    lastUpdated: "8 mins ago",
    priority: true,
  },
  {
    id: "EMS-1309",
    campaignName: "Azure Dinner Setup Confirmed",
    resortName: "Azure Cliff Suites",
    tenantName: "Azure Palms Hospitality",
    channel: "SMS",
    messageType: "Booking Confirmation",
    audienceType: "Guests",
    sendStatus: "Sent",
    priorityLevel: "Normal",
    deliveryWindow: "Released at 10:15 AM",
    owner: "Paula Ramos",
    note: "Guest received final dinner setup confirmation and arrival note.",
    lastUpdated: "18 mins ago",
    priority: false,
  },
  {
    id: "EMS-1310",
    campaignName: "Wave Hall Corporate Proposal",
    resortName: "Blue Reef Escapes",
    tenantName: "Blue Reef Escapes",
    channel: "Email",
    messageType: "Booking Confirmation",
    audienceType: "Leads",
    sendStatus: "Draft",
    priorityLevel: "Urgent",
    deliveryWindow: "Must release before 4:00 PM",
    owner: "Janine Castro",
    note: "Proposal email is waiting on final AV inclusions and revised contract copy.",
    lastUpdated: "5 mins ago",
    priority: true,
  },
];
